[build-system]
requires = ["setuptools", "wheel", "pybind11", "conan"]
build-backend = "setuptools.build_meta"

[project]
name = "test_wheel"
version = "0.1.0"
description = "Minimal pybind11 + ceres-solver demo with Conan"
requires-python = ">=3.8"
