name: Build wheels

on:
  push:
    tags:
      - "v*"   # ex: v1.0.0
  workflow_dispatch:

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: 'x64'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.20.0

      - name: Build wheels
        run: |
          cibuildwheel --output-dir dist
        env:
          CIBW_ARCHS_MACOS: x86_64
          CIBW_BEFORE_BUILD: >
            pip install conan && conan profile detect --force && conan install . --output-folder=build --build=missing &&
            cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          CIBW_SKIP: "pp* *-win32 *-manylinux_i686 *-musllinux_i686 *-macosx_10_*-x86_64"
          CIBW_ENVIRONMENT: >
            CMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake

      # Upload des artefacts
      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/*
