name: Build wheels

on:
  push:
    tags:
      - "v*"   # ex: v1.0.0
  workflow_dispatch:

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      # Installer Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: 'x64'

      # Installer cibuildwheel et conan
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.20.0 conan

      # Si besoin, configurer Conan pour GCC/Clang (Linux) ou MinGW (Windows)
      - name: Conan install
        run: |
          mkdir build
          conan profile detect --force
          conan install . --output-folder=build --build=missing

      # Lancer cibuildwheel (qui lancera la compilation et générera les wheels)
      - name: Build wheels
        run: |
          cibuildwheel --output-dir dist
        env:
          CIBW_SKIP: pp*  # skip pypy si pas besoin
          CIBW_ENVIRONMENT: >
            CMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake

      # Upload des artefacts
      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/*
